[package]
name = "wynnmap-types"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
crc32fast = "1.4.2"
serde = { version = "1.0.218", features = ["derive", "rc"] }
uuid = { version = "1.15.1", features = ["serde"] }
